spring:
  datasource1:
#    url: jdbc:mysql://47.114.75.143:3916/zhxfz?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    url: jdbc:mysql://47.93.37.47:3916/zhxfz?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    jdbc-url: jdbc:mysql://192.168.3.27:3306/D_6201LZ?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Boyang_8594079
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
    validation-query: SELECT 1 FROM DUAL
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    min-evictable-idle-time-millis: 25200000
    time-between-eviction-runs-millis: 60000
    remove-abandoned: true
    remove-abandoned-timeout: 1800
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20

  datasource2:
    jdbc-url: jdbc:oracle:thin:@152.136.151.164:1521:clptdb
    username: YBSS
    password: YBSS_RAC
    driver-class-name: oracle.jdbc.driver.OracleDriver

